### ISSUE TITLE
Sidebar partly hidden on sub-HD screen

### ISSUE THREAD

**Issue by lentzi90** [SaswatPadhi/purity-jekyll-theme#2]
On my chromebook (HP chromebook 14) the sidebar is partly hidden. Screen resolution is 1366x768 and I have a dock along one side so the effective width is a bit less than 1366px.

Here is a picture of the situation.
![purity-problem](https://cloud.githubusercontent.com/assets/9117693/19182294/bc6ea84a-8c72-11e6-91a6-50d703fbe23f.png)

**Comment by SaswatPadhi** [comment]
Thanks for the report @lentzi90 :+1: I'm glad you tried this theme.
